kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "database" 
  annotations:
    openshift.io/build-config.name: database
  labels:
    build: database
    buildconfig: database
    openshift.io/build-config.name: database
    openshift.io/build.start-policy: Serial
spec:
  source:
    contextDir: "containers/database"
    git:
      ref: main
      uri: 'https://github.com/stevshil/monitoring-lab.git'
    type: Git
  strategy:
   type: Docker
   dockerStrategy:
    dockerfilePath: .
  output: 
    to:
      kind: "ImageStreamTag"
      name: "database:latest"
