kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "moodle"
  annotations:
    openshift.io/build-config.name: moodle
  labels:
    build: moodle
    buildconfig: moodle
    openshift.io/build-config.name: moodle
    openshift.io/build.start-policy: Serial
spec:
  source:
    contextDir: "containers/moodle"
    git:
      ref: main
      uri: 'https://github.com/stevshil/monitoring-lab.git'
    type: Git
  strategy:
   type: Docker
   dockerStrategy:
    dockerfilePath: .
  output:
    to:
      kind: "ImageStreamTag"
      name: "moodle:latest"
