kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "prometheus"
  annotations:
    openshift.io/build-config.name: prometheus
  labels:
    build: prometheus
    buildconfig: prometheus
    openshift.io/build-config.name: prometheus
    openshift.io/build.start-policy: Serial
spec:
  source:
    contextDir: "containers/prometheus"
    git:
      ref: main
      uri: 'https://github.com/stevshil/monitoring-lab.git'
    type: Git
  strategy:
   type: Docker
   dockerStrategy:
    dockerfilePath: .
  output:
    to:
      kind: "ImageStreamTag"
      name: "prometheus:latest"
